### PR TITLE
Kerberos

### PR DESCRIPTION
**Pull request by jrs53**
Updating Hadoop version to fix TGT renewal with Kerberos

### CODE REVIEW

**Comment by jahhulbert-ccri** [comment]
@jrs53 does Kerberos not work with less than 2.7.3 ?

**Comment by jahhulbert-ccri** [comment]
I like 2.7.3 lets go with it

**Comment by jrs53** [comment]
There were a few changes to add the keytab path as a parameter for the Processor, plus fixing param validation. Later, I discovered the requirement to periodically try to renew the Kerberos TGT and while that code works fine outside of NiFi with Hadoop 2.6.0, it didn't work properly inside NiFi hence the new version. Afraid I didn't test anything other than 2.7.3.

**Comment by jahhulbert-ccri** [comment]
weird. the PR files only shows the one pom change...

https://github.com/geomesa/geomesa-nifi/pull/24/files

I'll try to do a command line merge squash to look before merging.

**Comment by jrs53** [comment]
@jnh5y merged the first set of changes already, so the only one left is the Hadoop version. Guess I should have created a separate PR rather than push to my branch - apologies

**Comment by jahhulbert-ccri** [comment]
ah :) no problem!

**Pull request merged**
